### ISSUE TITLE
localisation issue on installation file

### ISSUE THREAD

**Issue by scchrodinger** [KoBruhh/Crust#1]
uk's keywords are wrong![Screenshot_20230122-174034_GitHub.jpg](https://user-images.githubusercontent.com/118077794/213921722-8e688d1e-4821-4d94-8e4f-cb8fcef02f88.jpg)

**Comment by orhnk** [comment]
Sorry. I am late, It was holiday season I couldn't check these for two weeks.
Now I fixed it. But need someone to confirm me because I have no Ukrainian native to do so.

change:
текст редактор -> текстовий редактор
                                  ^^^^^^^^^^^^^^^^^-- Verified by Google

![Screenshot from 2023-02-11 15-18-35](https://user-images.githubusercontent.com/101834410/218257614-120364ff-48e9-44c6-a02e-9c4958965d06.png)
![Screenshot from 2023-02-11 15-18-59](https://user-images.githubusercontent.com/101834410/218257616-0653f90c-4ab5-485e-be04-7905fbd484bd.png)
